-- ============================================================
-- SQL SCHEMA FOR KAGUM (Kumpulan Administrasi Guru Madrasah)
-- Import file ini di phpMyAdmin pada cPanel Hosting Anda
-- ============================================================

CREATE TABLE IF NOT EXISTS `app_data` (
  `data_key` VARCHAR(100) NOT NULL PRIMARY KEY,
  `data_value` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed Initial Data (Data Utama Aplikasi KAGUM)
INSERT INTO `app_data` (`data_key`, `data_value`) VALUES
('kagum_schoolProfile', '{"namaMadrasah":"MIN 1 Purbalingga","alamatMadrasah":"Jalan Raya Krangean RT 01 RW 01 Kec. Kertanegara Kab. Purbalingga Prov. Jawa Tengah","namaKepala":"Abdul Kosim, S.Ag., M.Pd.I.","nipKepala":"197201042007011019","tahunAjaran":"2026/2027","semester":"Ganjil","logoUrl":"https://i.ibb.co.com/fYjbDbR7/Kementerian-Agama-new-logo.png","kopLaporan":{"line1":"KEMENTERIAN AGAMA REPUBLIK INDONESIA","line2":"KANTOR KEMENTERIAN AGAMA KABUPATEN PURBALINGGA","line3":"MADRASAH IBTIDAIYAH NEGERI 1 PURBALINGGA","line4":"Jalan Raya Krangean RT 01 RW 01 Kec. Kertanegara Kab. Purbalingga Prov. Jawa Tengah","line5":"Email: minsaga@madrasah.id | Website: www.min1purbalingga.sch.id | Telepon: (0281) 7700977","line6":""}}'),

('kagum_users', '[{"id":"usr-admin","name":"Administrator Utama","nip":"198501012010011001","kelas":"Semua Kelas","email":"kagum@minsaga.sch.id","password":"Adm1n456","role":"admin","avatarUrl":"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200"},{"id":"usr-admin-alt","name":"Administrator MIN 1","nip":"198501012010011001","kelas":"Semua Kelas","email":"admin@min1purbalingga.sch.id","password":"Adm1n456","role":"admin","avatarUrl":"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200"},{"id":"usr-guru1","name":"Sulis, S.Pd.I","nip":"198805122015032002","kelas":"Kelas IA","email":"sulis@madrasah.id","password":"guru123","role":"guru","avatarUrl":"https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200"}]'),

('kagum_subjects', '[{"id":"sbj-1","code":"AQH","name":"Qur\'an Hadis","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-2","code":"AAK","name":"Akidah Akhlak","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-3","code":"FIK","name":"Fikih","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-4","code":"SKI","name":"Sejarah Kebudayaan Islam","lingkupMateriCount":2,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-5","code":"BAR","name":"Bahasa Arab","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-6","code":"PPKN","name":"Pendidikan Pancasila","lingkupMateriCount":4,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-7","code":"BIND","name":"Bahasa Indonesia","lingkupMateriCount":4,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-8","code":"MTK","name":"Matematika","lingkupMateriCount":4,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-9","code":"IPAS","name":"Ilmu Pengetahuan Alam dan Sosial","lingkupMateriCount":4,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-10","code":"PJOK","name":"Pendidikan Jasmani, Olahraga dan Kesehatan","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-11","code":"SBDP","name":"Seni dan Budaya","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-12","code":"BING","name":"Bahasa Inggris","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75},{"id":"sbj-13","code":"BJAW","name":"Bahasa Jawa","lingkupMateriCount":3,"sumatifWeight":60,"sasWeight":40,"kktp":75}]'),

('kagum_students', '[{"id":"std-1","nisn":"0123456781","name":"Ahmad Raihan Pratama","birthPlace":"Purbalingga","birthDate":"2018-05-14","address":"Krangean RT 02 RW 01 Kertanegara","fatherName":"Bambang Pratama","motherName":"Siti Aminah","parentWa":"6281234567890","kelas":"Kelas IA"},{"id":"std-2","nisn":"0123456782","name":"Aisha Azzahra","birthPlace":"Purbalingga","birthDate":"2018-08-20","address":"Krangean RT 03 RW 01 Kertanegara","fatherName":"Muhamad Ridwan","motherName":"Nur Khasanah","parentWa":"6282345678901","kelas":"Kelas IA"},{"id":"std-3","nisn":"0123456783","name":"Bagas Prasetyo","birthPlace":"Purbalingga","birthDate":"2018-03-10","address":"Krangean RT 01 RW 01 Kertanegara","fatherName":"Sukarso","motherName":"Tri Wahyuni","parentWa":"6283456789012","kelas":"Kelas IA"}]')
ON DUPLICATE KEY UPDATE `updated_at` = NOW();
